### ISSUE TITLE
Multiple gateways

### ISSUE THREAD

**Issue by usul27** [ggravlingen/pytradfri#123]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home assistant

### Version of pytradfri
4.0.1 

### Expected behaviour
Works with multiple gateways

### Actual behaviour
undefined behaviour - lights are detected only on one gateway

I have 2 Tradfri gateways in different locations that are too far away to be controlled by a single gateway. Both are in the same network. With this configuration, HomeAssistant stops working properly, often one gateway is detected (most likely the one that response faster.

I see error messages like this:

2017-11-07 12:47:49 ERROR (MainThread) [coap] Fatal DTLS error: code 20
2017-11-07 12:47:49 ERROR (MainThread) [coap] Exception CancelledError() can not be represented as errno, setting -1.
2017-11-07 12:47:49 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 181, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/tradfri.py", line 66, in configuration_callback
    psk = yield from api_factory.generate_psk(callback_data.get('key'))
  File "/usr/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 193, in generate_psk
    self._psk = yield from self.request(command)
  File "/usr/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 149, in request
    result = yield from self._execute(api_commands)
  File "/usr/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 139, in _execute
    _, res = yield from self._get_response(msg)
  File "/usr/lib/python3.6/site-packages/pytradfri/api/aiocoap_api.py", line 92, in _get_response
    r = yield from pr.response
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 814, in _run_outer
    yield from cls._run(app_request, response, weak_observation, protocol, log, exchange_monitor_factory)
  File "/usr/lib/python3.6/site-packages/aiocoap/protocol.py", line 863, in _run
    blockresponse = yield from blockrequest.response
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
OSError: [Errno -1] No error information
2017-11-07 12:47:50 ERROR (MainThread) [coap] Fatal DTLS error: code 20
2017-11-07 12:47:50 ERROR (MainThread) [coap] Exception CancelledError() can not be represented as errno, setting -1.
2017-11-07 12:47:50 ERROR (MainThread) [coap] Fatal DTLS error: code 20
2017-11-07 12:47:50 ERROR (MainThread) [coap] Exception CancelledError() can not be represented as errno, setting -1.
2017-11-07 12:47:50 ERROR (MainThread) [coap] Fatal DTLS error: code 20

I'm not sure, if this is a problem of PyTradfri or HomeAssistant.

**Comment by ggravlingen** [comment]
This error is typically generated when there's a problem with the authentication. Given that you provide the correct KEY or PSK, there shouldn't be a problem with the latest version of pytradfri stand-alone lib to run against two gateways at the same time. Multiple IPs and PSKs can be stored by the lib in the json config file.

I'm not sure about support for multiple gateways in Home Assistant though so you might want to raise the issue in their git repo instead.

Please note that if you upgrade the stand-alone pytradfri lib to the latest version, you will break functionality in Home Assistant so I recommend against it if Home Assistant is your main platform.

**Comment by ggravlingen** [comment]
No activity in here for a while, closing issue.
