### ISSUE TITLE
Doesn't see E26 1000lm bulbs

### ISSUE THREAD

**Issue by alex-savin** [ggravlingen/pytradfri#142]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assitant v0.61.1

### Actual behaviour
Doesn't see bulbs (http://www.ikea.com/us/en/catalog/products/80339436/)

**Comment by Lakitna** [comment]
Could you please post the results of the following code (add it to one of the examples):

```
    devices_command = gateway.get_devices()
    devices_commands = api(devices_command)
    devices = api(devices_commands)

    for dev in devices:
        print(dev.raw)
    exit()
```

This will print all devices that are connected to your Gateway.

**Comment by ggravlingen** [comment]
@Lakitna I don't think another example file is the way to go, but perhaps add a few (commented out) lines in the async example file or something in the Wiki?

**Comment by alex-savin** [comment]
I have some very weird issue

```# python3 -i -m pytradfri IP_HERE
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
Please provide the 'Security Code' on the back of your Tradfri gateway: oQHIDDENnyb
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
DEBUG:pytradfri.api.libcoap_api:Executing IP_HERE post ['15011', '9063']: {'9090': 'ef4HIDDEN18'}
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/__main__.py", line 47, in <module>
    psk = api_factory.generate_psk(args.key)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 160, in generate_psk
    self._psk = self.request(Gateway().generate_psk(existing_psk_id))
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 92, in request
    return self._execute(api_commands)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 84, in _execute
    'Error executing request: {}'.format(err)) from None
pytradfri.error.RequestError: Error executing request: Command '['coap-client', '-u', 'Client_identity', '-k', 'oQHIDDENnyb', '-v', '0', '-m', 'post', '-f', '-', 'coaps://IP_HERE:5684/15011/9063']' returned non-zero exit status 1
>>> quit()
```

Then I decided to use Identity and Key from HA, with no success
```
# python3 -i -m pytradfri IP_HERE
DEBUG:pytradfri.api.libcoap_api:Executing IP_HERE get ['15001']
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/__main__.py", line 61, in <module>
    devices_commands = api(gateway.get_devices())
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 92, in request
    return self._execute(api_commands)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 84, in _execute
    'Error executing request: {}'.format(err)) from None
pytradfri.error.RequestError: Error executing request: Command '['coap-client', '-u', 'IDENTITY_HERE', '-k', 'KEY_HERE', '-v', '0', '-m', 'get', 'coaps://IP_HERE:5684/15001']' returned non-zero exit status 1
>>> quit()
```

**Comment by Lakitna** [comment]
@ggravlingen In that case, I'd say Wiki. That will make it easier when a newbie opens an issue because we can simply link to the script. I've also made a (pretty comprehensive) script that should work great for this. https://gist.github.com/Lakitna/264bcc4a29cd150e4bf003bbde07cb63

**Comment by Lakitna** [comment]
That is weird. I've tried to duplicate your error, but I can only get a `RequestTimeout`, not a `RequestError`. Have you installed libcoap using https://github.com/ggravlingen/pytradfri/blob/master/script/install-coap-client.sh ?

**Comment by alex-savin** [comment]
Recompiling of lib helped me out
```
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI bulb E26 WS opal 980lm","3311":[{"5850":0,"5851":121,"5717":0,"5711":370,"5709":30138,"5710":26909,"5706":"f1e0b5","9003":0}],"5750":2,"9002":1514479978,"9020":1516669615,"9003":65538,"9054":0,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E26 WS opal 980lm","2":"","3":"1.2.217","6":1}}
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI bulb E26 WS opal 980lm 2","3311":[{"5850":0,"5851":121,"5717":0,"5711":370,"5709":30138,"5710":26909,"5706":"f1e0b5","9003":0}],"5750":2,"9002":1514480038,"9020":1516669615,"9003":65539,"9054":0,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E26 WS opal 980lm","2":"","3":"1.2.217","6":1}}
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI bulb E26 WS opal 980lm 3","3311":[{"5850":0,"5851":254,"5717":0,"5711":370,"5709":30138,"5710":26909,"5706":"f1e0b5","9003":0}],"5750":2,"9002":1514480905,"9020":1516669615,"9003":65540,"9054":0,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E26 WS opal 980lm","2":"","3":"1.2.217","6":1}}
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI remote control","5750":0,"9002":1514412717,"9020":1516663999,"9003":65536,"9054":0,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI remote control","2":"","3":"1.2.214","6":3,"9":87},"15009":[{"9003":0}]}
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI remote control 2","5750":0,"9002":1514479897,"9020":1515377188,"9003":65537,"9054":0,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI remote control","2":"","3":"1.2.214","6":3,"9":60},"15009":[{"9003":0}]}
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI remote control 3","5750":0,"9002":1516392814,"9020":1516655109,"9003":65541,"9054":0,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI remote control","2":"","3":"1.2.214","6":3,"9":87},"15009":[{"9003":0}]}
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI bulb E26 CWS opal 600lm","3311":[{"5850":0,"5851":254,"5707":21064,"5708":65279,"5709":19661,"5710":39321,"5706":"0","9003":0}],"5750":2,"9002":1516392888,"9020":1516659747,"9003":65542,"9054":0,"9019":0,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E26 CWS opal 600lm","2":"","3":"1.3.002","6":1}}
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI remote control 4","5750":0,"9002":1516393710,"9020":1516657397,"9003":65543,"9054":0,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI remote control","2":"","3":"1.2.214","6":3,"9":60},"15009":[{"9003":0}]}
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI bulb E26 CWS opal 600lm 2","3311":[{"5850":1,"5851":254,"5707":21064,"5708":65279,"5709":19661,"5710":39321,"5706":"0","9003":0}],"5750":2,"9002":1516394564,"9020":1516669071,"9003":65544,"9054":0,"9019":0,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E26 CWS opal 600lm","2":"","3":"1.3.002","6":1}}
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI bulb E26 opal 1000lm","5750":1,"9002":1516394898,"9020":1516669816,"9003":65545,"9054":0,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E26 opal 1000lm","2":"","3":"1.2.214","6":1}}
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI bulb E26 opal 1000lm 2","5750":1,"9002":1516395427,"9020":1516657538,"9003":65546,"9054":0,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E26 opal 1000lm","2":"","3":"1.2.214","6":1}}
```

**Comment by ggravlingen** [comment]
Problem solved, closing issue.

**Comment by Lakitna** [comment]
A bit premature @ggravlingen, the actual issue of the first post has not been solved yet.

@alex-savin It looks like the system has miscategorised your E26 non-spectrum lamps. Your other lamps (color and white spectrum) should work just fine. If that is the case I suggest deleting the faulty paired devices using the Ikea app and pairing them once more.

You can see if it worked if the last two lines of your output (the lines representing your non-spectrum lamps) have the key `3311` in them. Right now they do not.

**Comment by alex-savin** [comment]
@Lakitna Thanks for letting know that Issue not solved yet.

I found the solution how to fix it.
By default all the bulb came with firmware version 1.1.1.0-5.7.2.0 and till they updated, even after update. They were never discovered by pytrafri. I had to remove them from hub and re-pair back with new firmware (version 1.2.214)
