### ISSUE TITLE
Problems running demo

### ISSUE THREAD

**Issue by dogmatic69** [ggravlingen/pytradfri#149]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
stand alone

### Version of pytradfri
latest from `pip3 install`

### Expected behaviour
Demo found in repo should work

### Actual behaviour

Various issues with config files missing, tried creating even though it looks like the script should be generating it on first run.

Regardless of the config, I also get this hard fail.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/carlsutton/.local/lib/python3.6/site-packages/pytradfri/__main__.py", line 47, in <module>
    psk = api_factory.generate_psk(args.key)
  File "/home/carlsutton/.local/lib/python3.6/site-packages/pytradfri/api/libcoap_api.py", line 160, in generate_psk
    self._psk = self.request(Gateway().generate_psk(existing_psk_id))
  File "/home/carlsutton/.local/lib/python3.6/site-packages/pytradfri/api/libcoap_api.py", line 92, in request
    return self._execute(api_commands)
  File "/home/carlsutton/.local/lib/python3.6/site-packages/pytradfri/api/libcoap_api.py", line 79, in _execute
    return_value = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'coap-client': 'coap-client'
```

**Comment by ggravlingen** [comment]
This is the key: `FileNotFoundError: [Errno 2] No such file or directory: 'coap-client': 'coap-client'`. Please install the requirements as per the installation section in the README.

**Comment by dogmatic69** [comment]
I was using the instructions in the actual file for reference. nothing about coap. https://github.com/ggravlingen/pytradfri/blob/master/examples/debug_info.py#L5

Will check the readme now.

**Comment by dogmatic69** [comment]
Working now :+1: 

Not sure if it would be better to update the demo to point to the README or add the missing steps

**Comment by ggravlingen** [comment]
Great to hear! We'll leave it as is for now.
