### ISSUE TITLE
Crashes querying a hub with no groups defined.

### ISSUE THREAD

**Issue by petergspire** [ggravlingen/pytradfri#157]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Standalone on a Raspberry Pi
### Version of pytradfri
? (latest from github)
### Actual behaviour
Crashes when querying the groups and no groups are defined:

`DEBUG:pytradfri.api.libcoap_api:Executing 192.168.1.54 get ['15004']
DEBUG:pytradfri.api.libcoap_api:Received: []
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/Tradfri/pytradfri/pytradfri/__main__.py", line 66, in <module>
    group = groups[0]
IndexError: list index out of range`

**Comment by petergspire** [comment]
... and moods. I commented out the groups and moods calls and got to run without crashing.

**Comment by ggravlingen** [comment]
Are you running the command line interface or one of the example scripts?

**Comment by petergspire** [comment]
This is with the command line interface. Creating a dummy group with a bulb and a mood fixes it.

**Comment by ggravlingen** [comment]
@lwis what do you say, should we raise an exception here or just log an error? The gw seems to handle removing moods and groups altogether.

**Comment by lwis** [comment]
We could just check the lengths of things and then print a message saying "no groups found" or something along those lines. 

There's no issue with the API, just the examples.
