### ISSUE TITLE
IKEA trådfri control outlet 

### ISSUE THREAD

**Issue by jontek2** [ggravlingen/pytradfri#182]
Add missing support for the latest Trådfri product; a control outlet, https://www.ikea.com/se/sv/catalog/products/90356166/

**Comment by ggravlingen** [comment]
Do you have any output from pytradfri from a gateway with the plug connected?

**Comment by HansVanEijsden** [comment]
> Do you have any output from pytradfri from a gateway with the plug connected?

I have, some debug info:

```
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 post ['15011', '9063']: {'9090': '...'}
DEBUG:pytradfri.api.libcoap_api:Received: {"9091":"zgFACimmFoKoqIjm","9029":"1.4.0015"}
Generated PSK:  ...
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15001']
DEBUG:pytradfri.api.libcoap_api:Received: [65541,65540,65538,65542,65539,65543,65545,65546,65547,65548]
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15001', 65541]
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"Muurlicht Rechts","9002":1529675918,"9020":1536890465,"9003":65541,"9054":0,"5750":2,"9019":1,"3311":[{"9003":0,"5850":1,"5851":147,"5717":0,"5711":454,"5709":32977,"5710":27105,"5706":"efd275"}],"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb GU10 WS 400lm","3":"1.2.217","2":"","6":1}}
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15001', 65540]
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"Plafond","9002":1529675179,"9020":1536927891,"9003":65540,"9054":0,"5750":2,"9019":1,"3311":[{"9003":0,"5850":0,"5851":254,"5717":0,"5711":370,"5709":30138,"5710":26909,"5706":"f1e0b5"}],"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E27 WS opal 980lm","3":"1.2.217","2":"","6":1}}
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15001', 65538]
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"Stalamp Plafond","9002":1529674644,"9020":1536947136,"9003":65538,"9054":0,"5750":2,"9019":1,"3311":[{"9003":0,"5850":1,"5851":254,"5707":5440,"5708":49612,"5709":31976,"5710":27312,"5706":"0"}],"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E27 CWS opal 600lm","3":"1.3.002","2":"","6":1}}
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15001', 65542]
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"Muurlicht Links","9002":1529675969,"9020":1536947725,"9003":65542,"9054":0,"5750":2,"9019":1,"3311":[{"9003":0,"5850":1,"5851":147,"5717":0,"5711":454,"5709":32977,"5710":27105,"5706":"efd275"}],"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb GU10 WS 400lm","3":"1.2.217","2":"","6":1}}
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15001', 65539]
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"Tafellicht","9002":1529674695,"9020":1536968433,"9003":65539,"9054":0,"5750":2,"9019":1,"3311":[{"9003":0,"5850":0,"5851":250,"5717":0,"5711":250,"5709":30138,"5710":26909,"5706":"f5faf6"}],"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb GU10 WS 400lm","3":"1.2.217","2":"","6":1}}
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15001', 65543]
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"Glazenkast","9002":1536962280,"9020":1536966396,"9003":65543,"9054":0,"5750":3,"9019":1,"9084":" 35 6a df dc d1 c0 e2 a6 4c 98 52 c6 87 6c ba 74","3":{"0":"IKEA of Sweden","1":"TRADFRI control outlet","3":"1.4.020","2":"","6":1},"3312":[{"9003":0,"5850":0,"5851":254}]}
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15001', 65545]
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI remote control","9002":1536966391,"9020":1536966408,"9003":65545,"9054":0,"5750":1,"9019":1,"3":{"0":"IKEA of Sweden","9":60,"1":"TRADFRI remote control","3":"1.2.214","2":"","6":3}}
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15001', 65546]
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TV-Set","9002":1536966646,"9020":1536967295,"9003":65546,"9054":0,"5750":3,"9019":1,"9084":" af 5e bc 11 29 30 60 a2 4f 9e 5e b7 7 e 7e 95","3":{"0":"IKEA of Sweden","1":"TRADFRI control outlet","3":"1.4.020","2":"","6":1},"3312":[{"9003":0,"5850":1,"5851":254}]}
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15001', 65547]
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"Buislamp Hoek","9002":1536966996,"9020":1536967987,"9003":65547,"9054":0,"5750":3,"9019":1,"9084":" d0 c9 f0 eb dd d3 a6 4c f1 80 b 16 4e f5 88 10","3":{"0":"IKEA of Sweden","1":"TRADFRI control outlet","3":"1.4.020","2":"","6":1},"3312":[{"9003":0,"5850":0,"5851":254}]}
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15001', 65548]
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"Audioset","9002":1536968250,"9020":1536968280,"9003":65548,"9054":0,"5750":3,"9019":1,"9084":" 43 86 6e b5 6a df dc da d6 ce 9c 5a b4 63 a4 2a","3":{"0":"IKEA of Sweden","1":"TRADFRI control outlet","3":"1.4.020","2":"","6":1},"3312":[{"9003":0,"5850":0,"5851":254}]}
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15004']
DEBUG:pytradfri.api.libcoap_api:Received: [131073,131074,131075]
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15005', <pytradfri.command.Command object at 0x7f211a2c2f98>]
DEBUG:pytradfri.api.libcoap_api:Received: [131073,131074,131075]
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15010']
DEBUG:pytradfri.api.libcoap_api:Received: []
DEBUG:pytradfri.api.libcoap_api:Executing 10.0.1.11 get ['15011', '15012']
DEBUG:pytradfri.api.libcoap_api:Received: {"9107":0,"9076":10,"9023":"1.tradfri.pool.ntp.org","9093":0,"9061":0,"9059":1536969079,"9060":"2018-09-14T23:51:19.028176Z","9062":0,"9092":0,"9075":37,"9029":"1.4.15","9066":5,"9081":"7e21455204400117","9069":1530560572,"9082":false,"9080":60,"9083":"N/A","9054":0,"9055":0,"9071":1,"9072":9,"9073":13,"9074":23,"9077":28,"9078":1,"9079":0,"9106":0,"9105":0,"9200":"248cf9a7-5158-44ed-b4a7-89c6aa42033d"}
```
Let me know if you want more.

**Comment by ggravlingen** [comment]
```
{  
   "9001":"Audioset",
   "9002":1536968250,
   "9020":1536968280,
   "9003":65548,
   "9054":0,
   "5750":3,
   "9019":1,
   "9084":" 43 86 6e b5 6a df dc da d6 ce 9c 5a b4 63 a4 2a",
   "3":{  
      "0":"IKEA of Sweden",
      "1":"TRADFRI control outlet",
      "3":"1.4.020",
      "2":"",
      "6":1
   },
   "3312":[  
      {  
         "9003":0,
         "5850":0,
         "5851":254
      }
   ]
}
```

**Comment by ggravlingen** [comment]
Anyone up for testing the branch supporting wall plugs? Should work in theory but as I don't have one, I can't test it.

**Comment by HansVanEijsden** [comment]
Oh yes, I would love to test! I use the plugin for Domoticz (https://github.com/moroen/IKEA-Tradfri-plugin) which talks to pytradfri, but that plugin isn't ready yet.
If you have clear instructions on how I can test your branch of pytradfri then I would be happy to test it for you. I already cloned your fix_plug branch so I'm ready to go.

**Comment by ggravlingen** [comment]
In the examples, you should be able to replace `light_control` with `socket_control` and `light[0]` with `socket[0]` and thus turn it on and off.

I've updated one of the examples to show what I mean:
https://gist.github.com/ggravlingen/17a9c39a40c70c1343fe2eedc944b364

**Comment by HansVanEijsden** [comment]
I have installed it using the requirements file, with DTLSSocket. So yes, I guess the async version. 
Thanks for the update, I will test it now!

**Comment by HansVanEijsden** [comment]
It seems to do something. It lists all the devices (plugs included), but `Is on` doesn't match the status (tried with the plug on and off):

```
# python3 example_switches.py 10.0.1.11
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 76 bytes cleartext
decrypt_verify(): found 311 bytes cleartext
decrypt_verify(): found 306 bytes cleartext
decrypt_verify(): found 301 bytes cleartext
decrypt_verify(): found 293 bytes cleartext
decrypt_verify(): found 214 bytes cleartext
decrypt_verify(): found 302 bytes cleartext
decrypt_verify(): found 287 bytes cleartext
decrypt_verify(): found 307 bytes cleartext
decrypt_verify(): found 295 bytes cleartext
decrypt_verify(): found 291 bytes cleartext
[<65541 - Muurlicht Rechts (TRADFRI bulb GU10 WS 400lm)>, <65540 - Plafond (TRADFRI bulb E27 WS opal 980lm)>, <65538 - Stalamp Plafond (TRADFRI bulb E27 CWS opal 600lm)>, <65542 - Muurlicht Links (TRADFRI bulb GU10 WS 400lm)>, <65539 - Tafellicht (TRADFRI bulb GU10 WS 400lm)>]
[<65543 - Glazenkast (TRADFRI control outlet)>, <65546 - TV-Set (TRADFRI control outlet)>, <65547 - Buislamp Hoek (TRADFRI control outlet)>, <65548 - Audioset (TRADFRI control outlet)>]
Is on: False
Name: Audioset
decrypt_verify(): found 294 bytes cleartext
Traceback (most recent call last):
  File "example_switches.py", line 146, in <module>
    asyncio.get_event_loop().run_until_complete(run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "example_switches.py", line 142, in run
    yield from api(state_command)
  File "/usr/local/src/pytradfri/pytradfri/api/aiocoap_api.py", line 152, in request
    result = yield from self._execute(api_commands)
  File "/usr/local/src/pytradfri/pytradfri/api/aiocoap_api.py", line 109, in _execute
    if api_command.observe:
AttributeError: 'bool' object has no attribute 'observe'
Error in sys.excepthook:

Original exception was:
```

**Comment by ggravlingen** [comment]
OK, let's simplify things a bit. Can you download and rnu the gist again?

**Comment by HansVanEijsden** [comment]
Done! Here the complete output:

```
# python3 example_switches2.py 10.0.1.11
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 76 bytes cleartext
decrypt_verify(): found 214 bytes cleartext
decrypt_verify(): found 302 bytes cleartext
decrypt_verify(): found 287 bytes cleartext
decrypt_verify(): found 307 bytes cleartext
decrypt_verify(): found 295 bytes cleartext
decrypt_verify(): found 291 bytes cleartext
decrypt_verify(): found 311 bytes cleartext
decrypt_verify(): found 306 bytes cleartext
decrypt_verify(): found 301 bytes cleartext
decrypt_verify(): found 293 bytes cleartext
[<65543 - Glazenkast (TRADFRI control outlet)>, <65546 - TV-Set (TRADFRI control outlet)>, <65547 - Buislamp Hoek (TRADFRI control outlet)>, <65548 - Audioset (TRADFRI control outlet)>]
Error in sys.excepthook:

Original exception was:
```

P.S. the original example_async.py works fine though.

**Comment by ggravlingen** [comment]
OK, this statement works at least:
```
    # Print all sockets
    print(sockets)
````

I've updated the gist again to see if it works a few more lines.

**Comment by HansVanEijsden** [comment]
Okay, now I don't have any errors, yippie! But.. also no responses yet.
I tried all the 4 switches through the IKEA app, but no output. Here is the complete output:

```
# python3 example_switches3.py 10.0.1.11
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 76 bytes cleartext
decrypt_verify(): found 311 bytes cleartext
decrypt_verify(): found 306 bytes cleartext
decrypt_verify(): found 301 bytes cleartext
decrypt_verify(): found 293 bytes cleartext
decrypt_verify(): found 214 bytes cleartext
decrypt_verify(): found 302 bytes cleartext
decrypt_verify(): found 287 bytes cleartext
decrypt_verify(): found 307 bytes cleartext
decrypt_verify(): found 295 bytes cleartext
decrypt_verify(): found 291 bytes cleartext
[<65543 - Glazenkast (TRADFRI control outlet)>, <65546 - TV-Set (TRADFRI control outlet)>, <65547 - Buislamp Hoek (TRADFRI control outlet)>, <65548 - Audioset (TRADFRI control outlet)>]
Is on: False
Waiting for observation to end (2 mins)
Try altering any light in the app, and watch the events!
```

**Comment by ggravlingen** [comment]
Observation isn't turned on in the script, that's why you're not seeing anything. I think I might have spotted an error. While I provide a fix, please download the updated gist.

**Comment by HansVanEijsden** [comment]
Okay! The is the result with the updated gist (looks the same error as the first one):
```
# python3 example_switches4.py 10.0.1.11
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 76 bytes cleartext
decrypt_verify(): found 214 bytes cleartext
decrypt_verify(): found 302 bytes cleartext
decrypt_verify(): found 287 bytes cleartext
decrypt_verify(): found 307 bytes cleartext
decrypt_verify(): found 295 bytes cleartext
decrypt_verify(): found 291 bytes cleartext
decrypt_verify(): found 311 bytes cleartext
decrypt_verify(): found 306 bytes cleartext
decrypt_verify(): found 301 bytes cleartext
decrypt_verify(): found 293 bytes cleartext
[<65543 - Glazenkast (TRADFRI control outlet)>, <65546 - TV-Set (TRADFRI control outlet)>, <65547 - Buislamp Hoek (TRADFRI control outlet)>, <65548 - Audioset (TRADFRI control outlet)>]
Is on: False
Name: Glazenkast
Traceback (most recent call last):
  File "example_switches4.py", line 122, in <module>
    asyncio.get_event_loop().run_until_complete(run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "example_switches4.py", line 116, in run
    yield from api(state_command)
  File "/usr/local/src/pytradfri/pytradfri/api/aiocoap_api.py", line 152, in request
    result = yield from self._execute(api_commands)
  File "/usr/local/src/pytradfri/pytradfri/api/aiocoap_api.py", line 109, in _execute
    if api_command.observe:
AttributeError: 'bool' object has no attribute 'observe'
Error in sys.excepthook:

Original exception was:
```

**Comment by ggravlingen** [comment]
I've pushed an update to the branch that might do the trick. Can you please pull it and try again?

**Comment by HansVanEijsden** [comment]
Thanks, done! 😃 
```
# git pull
remote: Counting objects: 4, done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/ggravlingen/pytradfri
   a9c6c79..0d60412  fix_plug   -> origin/fix_plug
Updating a9c6c79..0d60412
Fast-forward
 pytradfri/socket.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
```
Just to be sure:
```
# git checkout fix_plug
Already on 'fix_plug'
Your branch is up to date with 'origin/fix_plug'.
```
And I did a fresh download of your gist.
Results:
```
# python3 example_switches5.py 10.0.1.11
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 76 bytes cleartext
decrypt_verify(): found 214 bytes cleartext
decrypt_verify(): found 302 bytes cleartext
decrypt_verify(): found 287 bytes cleartext
decrypt_verify(): found 307 bytes cleartext
decrypt_verify(): found 295 bytes cleartext
decrypt_verify(): found 291 bytes cleartext
decrypt_verify(): found 311 bytes cleartext
decrypt_verify(): found 306 bytes cleartext
decrypt_verify(): found 301 bytes cleartext
decrypt_verify(): found 293 bytes cleartext
[<65543 - Glazenkast (TRADFRI control outlet)>, <65546 - TV-Set (TRADFRI control outlet)>, <65547 - Buislamp Hoek (TRADFRI control outlet)>, <65548 - Audioset (TRADFRI control outlet)>]
Is on: False
Name: Glazenkast
Traceback (most recent call last):
  File "example_switches5.py", line 122, in <module>
    asyncio.get_event_loop().run_until_complete(run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "example_switches5.py", line 116, in run
    yield from api(state_command)
  File "/usr/local/src/pytradfri/pytradfri/api/aiocoap_api.py", line 152, in request
    result = yield from self._execute(api_commands)
  File "/usr/local/src/pytradfri/pytradfri/api/aiocoap_api.py", line 109, in _execute
    if api_command.observe:
AttributeError: 'bool' object has no attribute 'observe'
Error in sys.excepthook:

Original exception was:
```

**Comment by ggravlingen** [comment]
Hmm

**Comment by HansVanEijsden** [comment]
If you need SSH access, just let me know. I run it in a simple local Docker instance 😉

**Comment by ggravlingen** [comment]
I added an example to the branch (in the examples folder) and put back some code that relates to observations. Please give it a go. :)

**Comment by HansVanEijsden** [comment]
Hehehe done! Here's the output:
```
# git pull
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 2), reused 4 (delta 2), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/ggravlingen/pytradfri
   0d60412..a561269  fix_plug   -> origin/fix_plug
Updating 0d60412..a561269
Fast-forward
 examples/example_socket_async.py | 136 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 136 insertions(+)
 create mode 100644 examples/example_socket_async.py
root@Ubuntu:/usr/local/src/pytradfri# cd examples/
root@Ubuntu:/usr/local/src/pytradfri/examples# python3 example_socket_async.py 10.0.1.11
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 76 bytes cleartext
decrypt_verify(): found 311 bytes cleartext
decrypt_verify(): found 306 bytes cleartext
decrypt_verify(): found 301 bytes cleartext
decrypt_verify(): found 293 bytes cleartext
decrypt_verify(): found 214 bytes cleartext
decrypt_verify(): found 302 bytes cleartext
decrypt_verify(): found 287 bytes cleartext
decrypt_verify(): found 307 bytes cleartext
decrypt_verify(): found 295 bytes cleartext
decrypt_verify(): found 291 bytes cleartext
[<65543 - Glazenkast (TRADFRI control outlet)>, <65546 - TV-Set (TRADFRI control outlet)>, <65547 - Buislamp Hoek (TRADFRI control outlet)>, <65548 - Audioset (TRADFRI control outlet)>]
Is on: False
Name: Audioset
decrypt_verify(): found 294 bytes cleartext
Traceback (most recent call last):
  File "example_socket_async.py", line 136, in <module>
    asyncio.get_event_loop().run_until_complete(run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "example_socket_async.py", line 130, in run
    yield from api(state_command)
  File "/usr/local/src/pytradfri/pytradfri/api/aiocoap_api.py", line 152, in request
    result = yield from self._execute(api_commands)
  File "/usr/local/src/pytradfri/pytradfri/api/aiocoap_api.py", line 109, in _execute
    if api_command.observe:
AttributeError: 'bool' object has no attribute 'observe'
Error in sys.excepthook:

Original exception was:
```
```
# python3 --version
Python 3.6.5
```
```
# uname -a
Linux Ubuntu 3.10.105 #23739 SMP Tue Jul 10 00:16:57 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ggravlingen** [comment]
I have to give this one a bit of a thought.

**Comment by HansVanEijsden** [comment]
No problem. I'm happy to test further (although tomorrow afternoon I'll be gone until the night).  Thanks for your time and I'll keep an eye on my mail notifications.

**Comment by ggravlingen** [comment]
I just spotted another error I had made. It's been fixed and pushed to Github.

**Comment by HansVanEijsden** [comment]
At least, `Is on: False` and `Is on: True` are working now, displaying the state of the socket (before the script ends with that Traceback). 👍🏻

**Comment by ggravlingen** [comment]
Great! That was my last fix :)

**Comment by lwis** [comment]
@ggravlingen looks like a boolean is being passed to the observation, rather than the `Command`.

https://gist.github.com/ggravlingen/17a9c39a40c70c1343fe2eedc944b364#file-gistfile1-txt-L130

`state_command` is actually being assigned to a boolean.

Also yes, ATTR_LIGHT_STATE should be renamed to ATTR_DEVICE_STATE if it's used more widely.

**Comment by ggravlingen** [comment]
@lwis OMG two equal signs in a row is never a good sign... Thanks! :blush: 

I'll refactor to ATTR_DEVICE_STATE.

**Comment by ggravlingen** [comment]
@HansVanEijsden can you please give the example script another go? I just updated it based on the suggestion made by @lwis.

**Comment by HansVanEijsden** [comment]
Hi @ggravlingen thanks for your patience, I just came home.
Good news: it works! As soon as I run the script, the socket turns on. And if I turn off the socket by the app or external remote, the scripts displays the new state (and then it quits, but no problem). 👍🏻 

```
i# git pull
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 22 (delta 13), reused 21 (delta 12), pack-reused 0
Unpacking objects: 100% (22/22), done.
From https://github.com/ggravlingen/pytradfri
   4bde50f..361c39b  fix_plug   -> origin/fix_plug
Updating 4bde50f..361c39b
Fast-forward
 examples/example_socket_async.py |  7 ++++---
 pytradfri/const.py               |  2 +-
 pytradfri/device.py              |  6 +++---
 pytradfri/group.py               |  6 +++---
 pytradfri/smart_task.py          | 10 +++++-----
 pytradfri/socket.py              |  6 +++---
 tests/test_device.py             | 31 +++++++++++++++----------------
 7 files changed, 34 insertions(+), 34 deletions(-)
```
```
# python3 example_socket_async.py 10.0.1.11
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 76 bytes cleartext
decrypt_verify(): found 311 bytes cleartext
decrypt_verify(): found 306 bytes cleartext
decrypt_verify(): found 301 bytes cleartext
decrypt_verify(): found 293 bytes cleartext
decrypt_verify(): found 214 bytes cleartext
decrypt_verify(): found 302 bytes cleartext
decrypt_verify(): found 287 bytes cleartext
decrypt_verify(): found 307 bytes cleartext
decrypt_verify(): found 295 bytes cleartext
decrypt_verify(): found 291 bytes cleartext
[<65543 - Glazenkast (TRADFRI control outlet)>, <65546 - TV-Set (TRADFRI control outlet)>, <65547 - Buislamp Hoek (TRADFRI control outlet)>, <65548 - Audioset (TRADFRI control outlet)>]
Is on: False
Name: Audioset
decrypt_verify(): found 294 bytes cleartext
Received message for: <Socket #0 - name: Glazenkast, state: off>
decrypt_verify(): found 288 bytes cleartext
Received message for: <Socket #0 - name: TV-Set, state: off>
decrypt_verify(): found 296 bytes cleartext
Received message for: <Socket #0 - name: Buislamp Hoek, state: off>
decrypt_verify(): found 292 bytes cleartext
Received message for: <Socket #0 - name: Audioset, state: off>
decrypt_verify(): found 8 bytes cleartext
Waiting for observation to end (10 secs)
decrypt_verify(): found 294 bytes cleartext
Received message for: <Socket #0 - name: Audioset, state: on>
decrypt_verify(): found 294 bytes cleartext
Received message for: <Socket #0 - name: Audioset, state: off>
WARNING:root:Observation deleted without explicit cancellation
WARNING:root:Observation deleted without explicit cancellation
WARNING:root:Observation deleted without explicit cancellation
WARNING:root:Observation deleted without explicit cancellation
Error in sys.excepthook:

Original exception was:
```

**Comment by ggravlingen** [comment]
Great news, then it works! It should quit after 10 seconds (there's a sleep somewhere near the end of the script.) You can try turning on the socket by changing the last False to True.

I'll clean up the code and merge the pr.

**Comment by ggravlingen** [comment]
5.6.0 (available in pypi) has basic support for wall plugs. Thanks for helping out adding support!
