### ISSUE TITLE
not able to runn any sample code, missing requirements?

### ISSUE THREAD

**Issue by lukicsl** [ggravlingen/pytradfri#194]
I installed the latest pytradfri, libcoap.
When I run any sample script I get errors.
e.g.
`lukics@ubuntu:~/pytradfri$ python3 ./debug_info.py 192.168.3.61
Please provide the 'Security Code' on the back of your Tradfri gateway: <code-here>
Traceback (most recent call last):
  File "264bcc4a29cd150e4bf003bbde07cb63/debug_info.py", line 55, in <module>
    psk = api_factory.generate_psk(args.key)
  File "/home/lukics/.local/lib/python3.6/site-packages/pytradfri/api/libcoap_api.py", line 164, in generate_psk
    self._psk = self.request(Gateway().generate_psk(existing_psk_id))
  File "/home/lukics/.local/lib/python3.6/site-packages/pytradfri/api/libcoap_api.py", line 96, in request
    return self._execute(api_commands, timeout=timeout)
  File "/home/lukics/.local/lib/python3.6/site-packages/pytradfri/api/libcoap_api.py", line 88, in _execute
    'Error executing request: {}'.format(err)) from None
pytradfri.error.RequestError: Error executing request: Command '['coap-client', '-u', 'Client_identity', '-k', '...', '-v', '0', '-m', 'post', '-f', '-', 'coaps://192.168.3.61:5684/15011/9063']' returned non-zero exit status 1.
`

**Comment by ggravlingen** [comment]
I edited out your key from the error message.

**Comment by ggravlingen** [comment]
Does it work if you run pytradfri from the docker? There's a file in scripts to run it.

**Comment by lukicsl** [comment]
In docker it works!
