### ISSUE TITLE
Traceback (most recent call last):   File "/usr/local/lib/python3.5/dist-packages/pytradfri/__main__.py", line 40, in <module>     identity = conf[args.host].get('identity') KeyError: '192.168.1.114'

### ISSUE THREAD

**Issue by Rishan123** [ggravlingen/pytradfri#233]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
I'm using pytradfri as a stand-alone(I think)
### Version of pytradfri
Don't know
### Expected behaviour
after it all runs, I should be able to write 'lights' in the python prompt and I should get my description of my light in an array
### Actual behaviour
`
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
Please provide the 'Security Code' on the back of your Tradfri gateway: XXXXXXXXXXX
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
DEBUG:pytradfri.api.libcoap_api:Executing 192.168.1.114 post ['15011', '9063']: {'9090': 'e859238eeb5244119a7bc24bbcb4a1e6'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/__main__.py", line 40, in <module>
    identity = conf[args.host].get('identity')
KeyError: '192.168.1.114'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/__main__.py", line 48, in <module>
    psk = api_factory.generate_psk(args.key)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 164, in generate_psk
    self._psk = self.request(Gateway().generate_psk(existing_psk_id))
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 96, in request
    return self._execute(api_commands, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 83, in _execute
    return_value = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'coap-client'
 
I did write my security code correctly

**Comment by twpayne** [comment]
You haven't installed libcoap. See the [installation instructions](https://github.com/ggravlingen/pytradfri#installation).

**Comment by Rishan123** [comment]
Thanks
