### ISSUE TITLE
pytradfri.error.RequestTimeout

### ISSUE THREAD

**Issue by lindehoff** [ggravlingen/pytradfri#25]
I get an RequestTimeout when I run `python3 -i -m pytradfri IP KEY`
```
DEBUG:pytradfri.coap_cli:Executing 10.6.2.153 get ['status']
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/pytradfri/__main__.py", line 18, in <module>
    api = api_factory(sys.argv[1], sys.argv[2])
  File "/usr/src/app/pytradfri/coap_cli.py", line 104, in api_factory
    request('get', ['status'])
  File "/usr/src/app/pytradfri/coap_cli.py", line 58, in request
    raise RequestTimeout() from None
pytradfri.error.RequestTimeout
```

**Comment by Finnsen** [comment]
Are you using the command as you show, or do you replace the IP with the gateway IP Adress and KEY with the key printed on the back of the gateway?

**Comment by SamuelBrucksch** [comment]
As you can see in the log the IP 10.6.2.153 was used. I have the same problem. I use IP 192.168.2.19 and key from bottom sticker.

**Comment by lindehoff** [comment]
The IP and Key are correct, I can ping the gateway. 
I did get it to work a couple of days ago but now when I try the same command I get this error.

I also believe thats its an network issue, when I port scan the gateway it has no open port, shouldn't i respond on port 5684?

The timeout error I get when I use the docker container, when I try on my MacOS machine I get this error:
```
 python3 -i -m pytradfri 10.6.2.153 MyKEY
DEBUG:pytradfri.coap_cli:Executing 10.6.2.153 get ['status']
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jacob/Dev/test/pytradfri/pytradfri/__main__.py", line 18, in <module>
    api = api_factory(sys.argv[1], sys.argv[2])
  File "/Users/jacob/Dev/test/pytradfri/pytradfri/coap_cli.py", line 104, in api_factory
    request('get', ['status'])
  File "/Users/jacob/Dev/test/pytradfri/pytradfri/coap_cli.py", line 61, in request
    'Error executing request: {}'.format(err)) from None
pytradfri.error.RequestError: Error executing request: Command '['coap-client', '-k', 'MyKEY', '-v', '0', '-m', 'get', 'coaps://10.6.2.153:5684/status']' returned non-zero exit status 1.
```

**Comment by balloob** [comment]
Does running this command work for you?

```
coap-client -k YOUR_KEY -v 0 -m get coaps://GATEWAY_IP:5684/15001
```

**Comment by lindehoff** [comment]
No, I get `coap-client: illegal option -- k`, but if I change ´-k´to `-T`I get:
```
coap-client -T KEY -v 0 -m get coaps://IP:5684/15001
v:1 t:0 tkl:0 c:1 id:51128
```

**Comment by otecfura** [comment]
You have probably old version of libcoap (4.1.1), you must have 4.1.2 version.

**Comment by lindehoff** [comment]
I get the same result in the docker container, I have also tried on an other client.

**Comment by balloob** [comment]
Our docker container is verified to work with our code, I use it for development.

**Comment by lindehoff** [comment]
@balloob Absolutely, it worked for me also in the beginning. There must be a network/gateway problem on my end, I just can't figure it out.

**Comment by lindehoff** [comment]
I have now reseted the Gateway and App and now it works again. 
Sorry for taking up your time, the problem was the gateway not your code.

**Comment by Julf** [comment]
I have a similar issue. Ping works just fine, but:
`python3 -i -m pytradfri nnn.nnn.nnn.nnn
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
Please provide the 'Security Code' on the back of your Tradfri gateway: XXXXXXXXXXXXXXXXXXXX
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
DEBUG:pytradfri.api.libcoap_api:Executing nnn.nnn.nnn.nnn post ['15011', '9063']: {'9090': 'XXXXXXXXXXXXXXXX'}
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/__main__.py", line 48, in <module>
    psk = api_factory.generate_psk(args.key)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 164, in generate_psk
    self._psk = self.request(Gateway().generate_psk(existing_psk_id))
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 96, in request
    return self._execute(api_commands, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/pytradfri/api/libcoap_api.py", line 85, in _execute
    raise RequestTimeout() from None
pytradfri.error.RequestTimeout
>>> 
`

**Comment by Rishan123** [comment]
> You have probably old version of libcoap (4.1.1), you must have 4.1.2 version.

How can you update it then?
Using Raspberry Pi

**Comment by Rishan123** [comment]
> I have now reseted the Gateway and App and now it works again.
> Sorry for taking up your time, the problem was the gateway not your code.

I have tried that and it still does not work.
