### ISSUE TITLE
'module' object has no attribute 'DEVNULL'

### ISSUE THREAD

**Issue by Bart1909** [ggravlingen/pytradfri#53]
Hi,

I'm trying to run pytradfri on my raspberry pi.

I've installed everything and try to start it with:
`python3 -i -m pytradfri 192.168.192.107 n65inIz...`

But then, I got the following error message:
`Traceback (most recent call last):
  File "/usr/lib/python3.2/runpy.py", line 161, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python3.2/runpy.py", line 74, in _run_code
    exec(code, run_globals)
  File "/home/pi/tradfri/pytradfri/pytradfri/__main__.py", line 19, in <module>
    api = api_factory(sys.argv[1], sys.argv[2])
  File "pytradfri/api/libcoap_api.py", line 131, in api_factory
    request(Command('get', ['status']))
  File "pytradfri/api/libcoap_api.py", line 78, in request
    return _execute(api_commands[0])
  File "pytradfri/api/libcoap_api.py", line 49, in _execute
    'stderr': subprocess.DEVNULL,
AttributeError: 'module' object has no attribute 'DEVNULL'`

What's the error and how can I fix it?

Best wishes

Tobi

**Comment by ggravlingen** [comment]
Running ```python3 -i -m pytradfri 192.168.0.129 xyz``` works for me. Are you sure you installed libcoap properly?

**Comment by Bart1909** [comment]
I've installed it on a second raspberry pi which is quite fresh installed. Now it works fine :-)
